let a=10;
let b=20;
let sum=a+b;
let sub=a-b;
let mul=a*b;
let div= a/b;
let mod=a%b;
let exp=a**b;
let increment=a++;
let decrement=b--;
let c=+b;
let d=-a;
document.write(sum);
document.write(sub);
document.write(mul);
document.write(div);
document.write(mod);
document.write(exp);
document.write(increment);
document.write(decrement);
document.write(c);
document.write(d);